#+TITLE: Chapter 1: Probability and Counting
#+PROPERTY: header-args:python :session *Python* :results output :exports both
#+STARTUP: latexpreview

#+BEGIN_SRC python
  import math
#+END_SRC

* Pebble World and the Naive Definition

If an experiment is performed, there will be one *outcome*.

The *Sample Space* /S/ is the set of all possible outcomes.

An *Event* /A/ is a set of outcomes, a subset of the sample space. We say
event A *occured* if the actual outcome is in the subset.

Picture this as a /pebble world/: The outcomes are all (equally sized)
pebbles. The sample space is the set of all pebbles. An event is a set
of pebbles. An experiment is the selection of one pebble. Since
they're equally sized, the probability of selecting any one pebble is
the same.

The *naive* definition of probability says the probability of an event /A/
is the number of outcomes in /A/, divided by the total number of
outcomes. Or

\begin{equation}
P_{\text{naive}}(A) = \frac{|A|}{|S|}
\end{equation}

From this, and the fact that \(|A^c|=|S|-|A|\), that \(P(A^c)=1-P(A)\).

The naive definition has two assumptions:

1. That S is finite
2. That each 'pebble' has equal mass.

* Sets

Probability is build on the idea of sets.

A set /S/ with /n/ elements has \(2^n\) subsets (including ∅ and /S/)

Sets are great because they give us lots of nice operations to use.
For example, De Morgan's laws.

\begin{align*}
(A \cup B)^c = A^c \cap B^c \\
(A \cap B)^c = A^c \cup B^c 
\end{align*}

Set notation gives us a language to talk about events. The following
is the event that the first of 10 coin flips is heads

\begin{equation}
A_1 = \{(1,s_2,...s_{10}) : s_j \in {0,1} \text{ for } 2 <= j <= 10\}
\end{equation}

And define events in terms of other events. If \( A_j \) is the event
that the \(j^{th}\) flip is heads then:

\begin{align*}
B = \bigcup_{j=1}^{10} A_j \\
C = \bigcap_{j=1}^{10} A_j \\
\end{align*}

B and C are the events that at least one throw is heads and /all/ throws
are heads.

* Methods for counting

When the numbers of pebbles is small, counting is OK. When the number
gets large, it get hard.

** Multiplication rule and Forking Paths

Say a shop sells ice cream. You can have a cone or cup. And there are
three flavors: Chocolate, vanilla, strawberry. You can draw a tree
which splits into two branches, representing the holder choice, and
then each of those splits into three, representing the ice cream
choice. Or you can do three then two, representing the opposite. This
can be represented as a tree.

#+begin_example
       .             .
      / \           /|\
     x   x         / | \
    /|\ /|\       x  x  x
    xxx xxx      /\ / \ /\
                x x x x x x
#+end_example

Thinking in terms of trees is helpful, even when the tree is too big
to physically draw.

In both cases we can see that the total number of outcomes is
3x2=2x3=6. This is the multiplication rule: if there are two
experiments with /a/ and /b/ outcomes, the total number of outcomes is
/axb/. (there are some caveats which we'll ignore for now).

If you buy two ice creams, the number of possibilities is 6x6=36.

What if you're interested in the number of combinations of the two ice
creams, like /(cupStraw, coneChoc)/. Still 36? No, because /(coneChoc,
coneChoc)/ is one of those combinations, but so is /(coneChoc,
coneChoc)/. They are the same, obviously, so should only be counted
once. There are 30 possibilities, with the duplicates are elminated.
Or if you're being really strict, and want to consider /(cupStraw,
coneChoc)/ the same as /(coneChoc, cupStraw)/, then there are 21.

* Choosing

How many ways can you choose /k/ objects from a total of /n/ objects? (A
good mental model here is selecting balls labelled 1-n from a jar).

This depends on a couple of things:

1. Are you replacing the balls after each choice?
2. Does order matter? That is, is selecting ball 1, then 2, the same
   as selecting 2, then 1?

It's easier if order matters, because it follows directly from the
multiplication rule. With replacement it's a simple matter of n
choices, k times. nxnxn.... \(n^k\). Without replacements, it's
similar, but after each 'pull' you have one less ball in the jar, so
instead of nxnxn..., it's nx(n-1)x(n-2)...(n-k+1)

Note that we /labelled/ the balls. This is important because it avoids
Leibniz's counting error: He thought the chances of getting a 11 when
rolling two 6-sided dice was equal, because both had a single outcome:
5 and 6, and 6 and 6. By treating the two dice as intistiguishable, he
missed the fact that you can get 11 from 5 and 6 /or/ 6 and 5, which are
different results.

If order doesn't matter, then the /binomial coefficient/ counts the
number of subsets of size /k/ of a set of size /n/

\begin{equation}
\binom{n}{k} = \frac{n(n-1)...(n-k+1)}{k!} = \frac{n!}{(n-k)!k!}
\end{equation}


Notice that this is the 'order matters' formula divded by /k!/. This is
because, if you list out the 'order-matters' subsets, then group them
by the elements in each set, there will be /k!/ in each group (i.e. the
number of permutations of k elements). So by dividing by /k!/, we're
effectively de-duplicating.

** Choice theorems

*** Complement

\begin{equation}
\binom{n}{k} = \binom{n}{n-k}
\end{equation}

This is easily shown by writing in terms of factorials, but a 'story
proof' is to observe that, if you want to committee of size /k/ from a
group of /n/ people, you can either choose the people on the committee
nCk. Or you can choose the people /not/ on the committee nC(n-k). The
two things are equivalent.

*** Vendermonde's identity

\begin{equation}
\binom{m+n}{k} = \sum_{j=0}^k \binom{m}{j}\binom{n}{k-j}
\end{equation}

*** chosing pairs

\begin{equation}
\frac{(2n)!}{2^n \cdot n!} = (2n-1)(2n-3)...3\cdot1
\end{equation}


* Non-naive definition of probability

** Axioms

A /probability space/ is a sample space /S/ and probability function /P/
mapping events to numbers between 0 and 1, such that /P(∅)=0/ and
/P(S)=1/.

/P(A u B)=P(A)+P(B)/ if /A/ and /B/ are *disjoint* (mutually exclusive)

We are still in pebble world: but now not all pebbles have to be the
same size, and you can have uncountable (continuous) sample spaces, in
which case the pebbles are more like a mass of mud.

Some properties derived from these axioms:

*Complement*: $P(A^C)=1-P(A)$

*Containment*: /A ⊆ B ⇒ P(A) ≤ P(B)/

*Inclusion-exclusion (2 sets)*: /P(AuB)=P(A)+P(B)-P(AnB)/

** Inclusion Exclusion

The IE property for 2 sets is a special case of the IE in general:

\begin{equation}
P(\bigcup_{i=1}^n A_i) = \sum_i{P(A_i)} - \sum_{i<j}{P(A_i \cap A_j)} + \sum_{i<j<k}{P(A_i \cap A_j \cap A_k)} - ... + (-1)^{n+1}P(A_1 \cap ... \cap A_n)
\end{equation}

The alternating plus and minus looks a bit odd. For some intuition on
why this is the case, consider /n=3/, with a venn diagram of three
circles A, B, C overlapping. You can add P(A) and P(B) and P(C), but
then you are double counting the overlap between A and B, A and C, and
B and C. So deduct P(AnB)+P(AnC)+P(BnC). But then you've deducted too
much: the intersection area of AnBnC was added 3 times when doing
P(A)+P(B)+P(C), but has now been deducted three times. So not being
counted at all, and you need to add it back.

/P(AuBuC)=P(A)+P(B)+P(C)-(P(AnB)+P(AnC)+P(BnC))+P(AnBnC)/

Inclusion-exclusion can be helpful when there symmetry between events.
Because there are n ways of choosing one event, nC2 ways of
choosing 2. So the kth term of the formula has nCk sub-terms in the
sum.


\begin{equation}
P(\bigcup_{i=1}^n A_i) = n{P(A_i)} - \binom{n}{2}{P(A_i \cap A_j)} + \binom{n}{3}{P(A_i \cap A_j \cap A_k)} - ... + (-1)^{n+1}P(A_1 \cap ... \cap A_n)
\end{equation}

Otherwise the sum can get very tedious.
